name: fetch-data
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install deps
        run: pip install requests nba_api
      - name: Fetch props and stats
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: |
          python fetch_props.py
          python fetch_stats.py
      - name: Commit CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add player_props_fetched.csv player_stats_fetched.csv
          git commit -m "Update fetched CSVs" || echo "no changes"
          git push
